name: CI/CD OCA

on:
  push:
    branches: ["main"] 
    tags: ["*"] 
              
jobs:
  build:
    runs-on: oca-self-hosted-runner
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v
 
      - name: Stop existing container
        run: docker rm -f ${{ vars.CONTAINER_NAME }} || true 

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: oca-frontend/Dockerfile.production 
          push: true
          tags: ${{ vars.DOCKER_IMAGE }}:latest    # change this to the right version of its image

      - name: Run new container
        run: docker run --name ${{ vars.CONTAINER_NAME }} -p ${{ vars.HOST_PORT }}:${{ vars.CONTAINER_PORT }} -d ${{ vars.DOCKER_IMAGE }}:latest

      - name: Prune unused Docker images
        run: docker system prune -f
